stages:
  prepare:
    cmd:
    - python src/data/make_dataset.py
    - python src/data/normalized_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    - src/data/normalized_dataset.py
    outs:
    - data/processed
  hyperparameter:
    cmd: python src/models/find_linear_regression_parameters.py
    deps:
    - data/processed
    - src/models/find_linear_regression_parameters.py
    outs:
    - models/lr_grid_search_estimator.pkl
    - models/lr_random_search_estimator.pkl
  train:
    cmd:
    - python src/models/train_linear_regression_model.py
    deps:
    - data/processed
    - src/models/train_linear_regression_model.py
    outs:
    - models/lr_model.joblib
  evaluate:
    cmd:
    - python src/models/evaluate_linear_regression_model.py
    deps:
    - data/processed
    - src/models/evaluate_linear_regression_model.py
    outs:
    - metrics/lr_metrics.json
    
